batch_size: 4
device: "cuda"  # Use "cuda" or "cpu"
epochs: 10
learning_rate: 5e-4
weight_decay: 0.01
save_every: 2  # Save every N epochs
resume_from: null  # Path to resume checkpoint or null
gradient_accumulation_steps: 4
checkpoint_path: "checkpoints"
gradient_clip_norm: 1.0

