epochs: 5
learning_rate: 1e-3
weight_decay: 0.01
save_every: 2  # Save every N epochs
resume_from: null  # Path to resume checkpoint or null
gradient_accumulation_steps: 4
checkpoint_path: "checkpoints"
gradient_clip_norm: 1.0

